spring.application.name=autoloc-api

# ===============================
# DATABASE MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# LOGS
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.tn.esprit.autoloc=INFO

# ===============================
# SERVER
# ===============================
server.port=8081